version: "3.8"
services:
  mysql:
    image: mysql:8.0 # Bạn có thể thay đổi phiên bản MySQL nếu cần
    environment:
      MYSQL_ROOT_PASSWORD: 12345 # Thay đổi mật khẩu root
      MYSQL_DATABASE: sale_db # Tên cơ sở dữ liệu bạn muốn tạo
      # MYSQL_USER: root # Tên người dùng
      # MYSQL_PASSWORD: 12345 # Mật khẩu của người dùng
    ports:
      - "3306:3306" # Mở cổng 3306 cho MySQL
    volumes:
      - db_data:/var/lib/mysql # Volume cho dữ liệu MySQL
      - ./sql_dump:/docker-entrypoint-initdb.d/ # Thư mục chứa các script SQL để import
  server:
  
volumes:
  db_data:
